name: Build Kernel

permissions:
  contents: write
  actions: write

on:
  workflow_call:

jobs:
  ## POCO
  build-poco-f4:
    name: "POCO F4"
    strategy:
      fail-fast: true
    uses: ./.github/workflows/build-poco-f4.yml
    secrets: inherit
    
